### ISSUE TITLE
PermissionError: [WinError 5] 

### ISSUE THREAD

**Issue by keyfour** [cdrx/docker-pyinstaller#16]
I got error after running:
```sh
docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows
```

Error output:
```
Installing collected packages: appdirs, cached-property, certifi, chardet, colorama, defusedxml, greenlet, gevent, idna, isodate, lxml, pip, pytz, urllib3, requests, requests-toolbelt, setuptools, six, wheel, zeep
  Running setup.py install for isodate: started
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
    Running setup.py install for isodate: finished with status 'done'
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Exception:
Traceback (most recent call last):
  File "c:\Python35\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access denied: 'C:\\users\\root\\Temp\\pip-vdu80sk3-uninstall\\python35\\scripts\\pip.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python35\lib\site-packages\pip\basecommand.py", line 209, in main
    logger.critical(
  File "c:\Python35\lib\site-packages\pip\commands\install.py", line 317, in run
  File "c:\Python35\lib\site-packages\pip\req\req_set.py", line 743, in install
  File "c:\Python35\lib\site-packages\pip\req\req_install.py", line 759, in commit_uninstall
    self.uninstalled.rollback()
  File "c:\Python35\lib\site-packages\pip\req\req_uninstall.py", line 142, in commit
    rmtree(self.save_dir)
  File "c:\Python35\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\Python35\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\Python35\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\Python35\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\Python35\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\Python35\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\Python35\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\Python35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\Python35\lib\shutil.py", line 378, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\Python35\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\Python35\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
PermissionError: [WinError 5] Access denied: 'C:\\users\\root\\Temp\\pip-vdu80sk3-uninstall\\python35\\scripts\\pip.exe'
```
My requirements:

* [requirements.txt](https://github.com/cdrx/docker-pyinstaller/files/1369400/requirements.txt)

**Comment by cdrx** [comment]
@keyfour this should be fixed now, could you please reopen the issue if you still see this error?
