### ISSUE TITLE
Getting Access denied on `.dist/windows`

### ISSUE THREAD

**Issue by mightymercado** [cdrx/docker-pyinstaller#75]
I'm getting `PermissionError: [WinError 5] Access denied: './dist/windows'` when doing  `sudo docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows`

Here is the last stack trace:
```
862 INFO: Python: 3.7.5
876 INFO: Platform: Windows-XP-5.1.2600
950 INFO: UPX is not available.
954 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
Traceback (most recent call last):
  File "c:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 746, in build
    os.makedirs(pth)
  File "c:\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access denied: './dist/windows'
```

**Comment by mightymercado** [comment]
nvm got it fixed. Just needed to chmod +x on the ./dist directory.
