### ISSUE TITLE
Strange temporary file error

### ISSUE THREAD

**Issue by virtuald** [cdrx/docker-pyinstaller#9]
```
docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows:python2
...
355 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 691, in build
    os.makedirs(pth)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] Invalid name: '/tmp\\*'
```

Have you seen this before?

**Comment by virtuald** [comment]
It seems that for some reason the volume I'm mounting isn't accessible to the container user. Adding an `ls -l /` at startup shows that user 1000 has permissions on the directory. 

I'm on docker 1.10 / Fedora 24. I'll dig some more.

**Comment by virtuald** [comment]
Ah, looks like an selinux issue.

http://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

**Comment by their** [comment]
@virtuald Is this Fedora only and the solution permissions? The same behavior occurs on Debian (with no selinux):

```
$ uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux

$ pwd
/home/user123/

$ docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows:python2

err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
934 INFO: PyInstaller: 3.2.1
935 INFO: Python: 2.7.12
937 INFO: Platform: Windows-7-6.1.7601-SP1
940 INFO: UPX is not available.
940 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
Traceback (most recent call last):
  File "C:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python27\lib\site-packages\PyInstaller\building\build_main.py", line 691, in build
    os.makedirs(pth)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] Invalid name: '/tmp\\*'
```

**Comment by virtuald** [comment]
Are you positive that it's not an selinux (or similar) error? I added `:Z` to the end of the volume path and it worked after that.

**Comment by their** [comment]
For some reason there is a Security-Alert issue:

```
dave@debian:~/Trumpocalypse/UI$ docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows:python2 "pyinstaller -y Trumpocalypse.py"

...

9041 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py27_32bit\_socket.pyd
9042 INFO: Updating resource type 24 name 2 language 1033
9065 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py27_32bit\pyexpat.pyd
9066 INFO: Updating resource type 24 name 2 language 1033
9077 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py27_32bit\select.pyd
9078 INFO: Updating resource type 24 name 2 language 1033
9086 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py27_32bit\_ctypes.pyd
9087 INFO: Updating resource type 24 name 2 language 1033
9101 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py27_32bit\bz2.pyd
9101 INFO: Updating resource type 24 name 2 language 1033
9121 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py27_32bit\unicodedata.pyd
9122 INFO: Updating resource type 24 name 2 language 1033
Security-Alert: try to store file outside of dist-directory. Aborting. 'Z:\\src\\build\\Trumpocalypse\\Trumpocalypse.exe.manifest'
```

**Comment by virtuald** [comment]
Did you try?

```
docker run -v "$(pwd):/src/:Z" cdrx/pyinstaller-windows:python2 "pyinstaller -y Trumpocalypse.py"
```

**Comment by their** [comment]
Yeah. Same issue.

**Comment by bmustiata** [comment]
As a side note, this might happen if in the current folder there is no `.spec` file. Probably in the `entrypoint.sh` there should be a check for that, because the error is very confusing.
